[17/04/03 22:34:50][INFO]:
Start to read and process the entries in input file ./log_input/log.txt:
[17/04/03 22:34:50][INFO]:
Reading and processing entry...
[17/04/03 22:35:28][INFO]:
Fail to process entry klothos.crl.research.digital.com - - [10/Jul/1995:16:45:50 -0400] "" 400 -
Traceback (most recent call last):
  File "./src/process_log.py", line 42, in <module>
    dict_entry = read_entry.read_entry(entry)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 107, in read_entry
    dictionary = format_standardize(hit)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 61, in format_standardize
    .format(entry_dict["Request"]))
TypeError: Type of request is not found in the entry: 

[17/04/03 22:36:09][INFO]:
Fail to process entry firewall.dfw.ibm.com - - [20/Jul/1995:07:34:34 -0400] "1/history/apollo/images/" 400 -
Traceback (most recent call last):
  File "./src/process_log.py", line 42, in <module>
    dict_entry = read_entry.read_entry(entry)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 107, in read_entry
    dictionary = format_standardize(hit)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 61, in format_standardize
    .format(entry_dict["Request"]))
TypeError: Type of request is not found in the entry: 1/history/apollo/images/

[17/04/03 22:36:09][INFO]:
Fail to process entry firewall.dfw.ibm.com - - [20/Jul/1995:07:53:24 -0400] "1/history/apollo/images/" 400 -
Traceback (most recent call last):
  File "./src/process_log.py", line 42, in <module>
    dict_entry = read_entry.read_entry(entry)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 107, in read_entry
    dictionary = format_standardize(hit)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 61, in format_standardize
    .format(entry_dict["Request"]))
TypeError: Type of request is not found in the entry: 1/history/apollo/images/

[17/04/03 22:36:11][INFO]:
Fail to process entry 128.159.122.20 - - [20/Jul/1995:15:28:50 -0400] "kƒûtxƒûtGƒûtÍƒû" 400 -
Traceback (most recent call last):
  File "./src/process_log.py", line 42, in <module>
    dict_entry = read_entry.read_entry(entry)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 107, in read_entry
    dictionary = format_standardize(hit)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 61, in format_standardize
    .format(entry_dict["Request"]))
TypeError: Type of request is not found in the entry: kƒûtxƒûtGƒûtÍƒû

[17/04/03 22:36:22][INFO]:
Fail to process entry 128.159.122.20 - - [24/Jul/1995:13:52:50 -0400] "kƒûtxƒûtGƒûtÍƒû" 400 -
Traceback (most recent call last):
  File "./src/process_log.py", line 42, in <module>
    dict_entry = read_entry.read_entry(entry)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 107, in read_entry
    dictionary = format_standardize(hit)
  File "/Users/yuan/Documents/Insight/src/read_entry.py", line 61, in format_standardize
    .format(entry_dict["Request"]))
TypeError: Type of request is not found in the entry: kƒûtxƒûtGƒûtÍƒû

[17/04/03 22:36:36][INFO]:
Reading and processing entries is finished.
[17/04/03 22:36:36][INFO]:
Output the blocked host activities to file ./log_output/blocked.txt
[17/04/03 22:36:36][INFO]:
Output the top ten busy hours to file ./log_output/hours.txt
[17/04/03 22:36:36][INFO]:
Output the top ten active hosts to file ./log_output/hosts.txt
[17/04/03 22:36:38][INFO]:
Output the top ten resources that consumes most bandwidth to file ./log_output/resources.txt
[17/04/03 22:36:38][INFO]:
Memory Usage : 510.20703125 MB
